static partial class Cpu {
    static void Op0x00() {}
    static void Op0x01() {}
    static void Op0x02() {}
    static void Op0x03() {}
    static void Op0x04() {}
    static void Op0x05() {}
    static void Op0x06() {}
    static void Op0x07() {}
    static void Op0x08() {}
    static void Op0x09() {}
    static void Op0x0A() {}
    static void Op0x0B() {}
    static void Op0x0C() {}
    static void Op0x0D() {}
    static void Op0x0E() {}
    static void Op0x0F() {}
    static void Op0x10() {}
    static void Op0x11() {}
    static void Op0x12() {}
    static void Op0x13() {}
    static void Op0x14() {}
    static void Op0x15() {}
    static void Op0x16() {}
    static void Op0x17() {}
    static void Op0x18() {}
    static void Op0x19() {}
    static void Op0x1A() {}
    static void Op0x1B() {}
    static void Op0x1C() {}
    static void Op0x1D() {}
    static void Op0x1E() {}
    static void Op0x1F() {}
    static void Op0x20() {}
    static void Op0x21() {}
    static void Op0x22() {}
    static void Op0x23() {}
    static void Op0x24() {}
    static void Op0x25() {}
    static void Op0x26() {}
    static void Op0x27() {}
    static void Op0x28() {}
    static void Op0x29() {}
    static void Op0x2A() {}
    static void Op0x2B() {}
    static void Op0x2C() {}
    static void Op0x2D() {}
    static void Op0x2E() {}
    static void Op0x2F() {}
    static void Op0x30() {}
    static void Op0x31() {}
    static void Op0x32() {}
    static void Op0x33() {}
    static void Op0x34() {}
    static void Op0x35() {}
    static void Op0x36() {}
    static void Op0x37() {}
    static void Op0x38() {}
    static void Op0x39() {}
    static void Op0x3A() {}
    static void Op0x3B() {}
    static void Op0x3C() {}
    static void Op0x3D() {}
    static void Op0x3E() {}
    static void Op0x3F() {}
    static void Op0x40() {}
    static void Op0x41() {}
    static void Op0x42() {}
    static void Op0x43() {}
    static void Op0x44() {}
    static void Op0x45() {}
    static void Op0x46() {}
    static void Op0x47() {}
    static void Op0x48() {}
    static void Op0x49() {}
    static void Op0x4A() {}
    static void Op0x4B() {}
    static void Op0x4C() {}
    static void Op0x4D() {}
    static void Op0x4E() {}
    static void Op0x4F() {}
    static void Op0x50() {}
    static void Op0x51() {}
    static void Op0x52() {}
    static void Op0x53() {}
    static void Op0x54() {}
    static void Op0x55() {}
    static void Op0x56() {}
    static void Op0x57() {}
    static void Op0x58() {}
    static void Op0x59() {}
    static void Op0x5A() {}
    static void Op0x5B() {}
    static void Op0x5C() {}
    static void Op0x5D() {}
    static void Op0x5E() {}
    static void Op0x5F() {}
    static void Op0x60() {}
    static void Op0x61() {}
    static void Op0x62() {}
    static void Op0x63() {}
    static void Op0x64() {}
    static void Op0x65() {}
    static void Op0x66() {}
    static void Op0x67() {}
    static void Op0x68() {}
    static void Op0x69() {}
    static void Op0x6A() {}
    static void Op0x6B() {}
    static void Op0x6C() {}
    static void Op0x6D() {}
    static void Op0x6E() {}
    static void Op0x6F() {}
    static void Op0x70() {}
    static void Op0x71() {}
    static void Op0x72() {}
    static void Op0x73() {}
    static void Op0x74() {}
    static void Op0x75() {}
    static void Op0x76() {}
    static void Op0x77() {}
    static void Op0x78() {}
    static void Op0x79() {}
    static void Op0x7A() {}
    static void Op0x7B() {}
    static void Op0x7C() {}
    static void Op0x7D() {}
    static void Op0x7E() {}
    static void Op0x7F() {}
    static void Op0x80() {}
    static void Op0x81() {}
    static void Op0x82() {}
    static void Op0x83() {}
    static void Op0x84() {}
    static void Op0x85() {}
    static void Op0x86() {}
    static void Op0x87() {}
    static void Op0x88() {}
    static void Op0x89() {}
    static void Op0x8A() {}
    static void Op0x8B() {}
    static void Op0x8C() {}
    static void Op0x8D() {}
    static void Op0x8E() {}
    static void Op0x8F() {}
    static void Op0x90() {}
    static void Op0x91() {}
    static void Op0x92() {}
    static void Op0x93() {}
    static void Op0x94() {}
    static void Op0x95() {}
    static void Op0x96() {}
    static void Op0x97() {}
    static void Op0x98() {}
    static void Op0x99() {}
    static void Op0x9A() {}
    static void Op0x9B() {}
    static void Op0x9C() {}
    static void Op0x9D() {}
    static void Op0x9E() {}
    static void Op0x9F() {}
    static void Op0xA0() {}
    static void Op0xA1() {}
    static void Op0xA2() {}
    static void Op0xA3() {}
    static void Op0xA4() {}
    static void Op0xA5() {}
    static void Op0xA6() {}
    static void Op0xA7() {}
    static void Op0xA8() {}
    static void Op0xA9() {}
    static void Op0xAA() {}
    static void Op0xAB() {}
    static void Op0xAC() {}
    static void Op0xAD() {}
    static void Op0xAE() {}
    static void Op0xAF() {}
    static void Op0xB0() {}
    static void Op0xB1() {}
    static void Op0xB2() {}
    static void Op0xB3() {}
    static void Op0xB4() {}
    static void Op0xB5() {}
    static void Op0xB6() {}
    static void Op0xB7() {}
    static void Op0xB8() {}
    static void Op0xB9() {}
    static void Op0xBA() {}
    static void Op0xBB() {}
    static void Op0xBC() {}
    static void Op0xBD() {}
    static void Op0xBE() {}
    static void Op0xBF() {}
    static void Op0xC0() {}
    static void Op0xC1() {}
    static void Op0xC2() {}
    static void Op0xC3() {}
    static void Op0xC4() {}
    static void Op0xC5() {}
    static void Op0xC6() {}
    static void Op0xC7() {}
    static void Op0xC8() {}
    static void Op0xC9() {}
    static void Op0xCA() {}
    static void Op0xCB() {}
    static void Op0xCC() {}
    static void Op0xCD() {}
    static void Op0xCE() {}
    static void Op0xCF() {}
    static void Op0xD0() {}
    static void Op0xD1() {}
    static void Op0xD2() {}
    static void Op0xD3() {}
    static void Op0xD4() {}
    static void Op0xD5() {}
    static void Op0xD6() {}
    static void Op0xD7() {}
    static void Op0xD8() {}
    static void Op0xD9() {}
    static void Op0xDA() {}
    static void Op0xDB() {}
    static void Op0xDC() {}
    static void Op0xDD() {}
    static void Op0xDE() {}
    static void Op0xDF() {}
    static void Op0xE0() {}
    static void Op0xE1() {}
    static void Op0xE2() {}
    static void Op0xE3() {}
    static void Op0xE4() {}
    static void Op0xE5() {}
    static void Op0xE6() {}
    static void Op0xE7() {}
    static void Op0xE8() {}
    static void Op0xE9() {}
    static void Op0xEA() {}
    static void Op0xEB() {}
    static void Op0xEC() {}
    static void Op0xED() {}
    static void Op0xEE() {}
    static void Op0xEF() {}
    static void Op0xF0() {}
    static void Op0xF1() {}
    static void Op0xF2() {}
    static void Op0xF3() {}
    static void Op0xF4() {}
    static void Op0xF5() {}
    static void Op0xF6() {}
    static void Op0xF7() {}
    static void Op0xF8() {}
    static void Op0xF9() {}
    static void Op0xFA() {}
    static void Op0xFB() {}
    static void Op0xFC() {}
    static void Op0xFD() {}
    static void Op0xFE() {}
    static void Op0xFF() {}
}